name: flutter_ui_1
description: "Flutter Lotto Simulator App - แอปจำลองการซื้อลอตเตอรี่"

# Prevent publishing to pub.dev
publish_to: 'none'

# Version
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies for Lotto App
  provider: ^6.0.0          # State management
  google_fonts: ^4.0.0      # Thai font support (Kanit)
  intl: ^0.18.0             # Number formatting and internationalization
  flutter_dotenv: ^6.0.0    # For .env config file
  socket_io_client: ^3.0.0  # WebSocket client for real-time communication

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Load .env file into app
  assets:
    - .env
